{{- if .Values.ingress.enabled -}}
{{- $fullName := include "catamel.fullname" . -}}
{{- $serviceName := include "catamel.fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
{{- $host := .Values.ingress.host -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "catamel.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
  - secretName: catamelservice
    hosts:
    - {{ $host }}
  rules:
    - host: catamelservice.esss.dk
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    - host: {{ $host }}
      http:
        paths:
          - path: /api
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
          - path: /explorer
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
          - path: /auth/msad
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
{{- end -}}